services:
  - type: web
    name: e_chat
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: e_chat_db
          property: connectionString

databases:
  - name: e_chat_db
    databaseName: echat
    user: echat
    plan: free
    region: singapore
